# Generated by Django 2.2.2 on 2022-05-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='pid',
            field=models.IntegerField(default='', null=True, verbose_name='子id'),
        ),
    ]
