# Generated by Django 2.2.2 on 2022-05-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220525_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_menu', models.CharField(default='', max_length=30, verbose_name='名称')),
                ('pid', models.IntegerField(default=0, verbose_name='子id')),
                ('status', models.IntegerField(default=1, verbose_name='状态0不可见/1可见')),
            ],
            options={
                'db_table': 'account_menu',
            },
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
