# Generated by Django 2.2.2 on 2022-05-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220525_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='pid',
            field=models.IntegerField(default='', verbose_name='子id'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.CharField(max_length=256, null=True, verbose_name='角色资源地址'),
        ),
    ]
