# Generated by Django 2.2.2 on 2022-06-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220527_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.IntegerField(default=0, verbose_name='用户等级'),
        ),
    ]
