# Generated by Django 2.2.2 on 2022-05-25 03:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='司机名')),
                ('phone', models.CharField(max_length=11, verbose_name='司机手机号')),
                ('status', models.IntegerField(default=0, verbose_name='司机状态0空闲1繁忙')),
            ],
            options={
                'db_table': 'logistics_driver',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_site', models.CharField(max_length=15, verbose_name='出发地')),
                ('from_site', models.CharField(max_length=15, verbose_name='目的地')),
                ('money', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='费用')),
            ],
            options={
                'db_table': 'logistics_site',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10, verbose_name='车牌号')),
                ('status', models.IntegerField(default=0, verbose_name='状态0空闲1繁忙')),
            ],
            options={
                'db_table': 'logistics_truck',
            },
        ),
        migrations.CreateModel(
            name='MailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=20, unique=True, verbose_name='快递单号')),
                ('name', models.CharField(max_length=10, verbose_name='商品名称')),
                ('sender', models.CharField(max_length=20, verbose_name='发件人')),
                ('receiver', models.CharField(max_length=20, verbose_name='收货人')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发货时间')),
                ('to_place', models.CharField(max_length=50, null=True, verbose_name='收货地址')),
                ('from_place', models.CharField(max_length=50, null=True, verbose_name='发货地址')),
                ('status', models.IntegerField(default=0, verbose_name='快递状态')),
                ('money', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='快递价格')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Driver', verbose_name='司机信息')),
                ('truck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Truck', verbose_name='货车信息')),
            ],
            options={
                'db_table': 'logistics_record',
            },
        ),
    ]
