# Generated by Django 2.2.2 on 2022-05-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailrecord',
            name='receiver_phone',
            field=models.CharField(default=None, max_length=13, verbose_name='收货人电话'),
            preserve_default=False,
        ),
    ]
