# Generated by Django 2.2.2 on 2022-05-25 03:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=20, verbose_name='订单唯一标识')),
                ('car_count', models.CharField(blank=True, max_length=20, null=True, verbose_name='车牌号')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2022, 5, 25, 3, 22, 40, 999950, tzinfo=utc), verbose_name='订单生成时间')),
                ('done_time', models.DateTimeField(blank=True, null=True, verbose_name='订单付款时间')),
                ('status', models.IntegerField(default=0, verbose_name='订单的支付状态')),
                ('total_pay', models.IntegerField(blank=True, null=True, verbose_name='实际支付金额')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good.Record')),
            ],
            options={
                'db_table': 'pay_order',
            },
        ),
    ]
