# Generated by Django 2.2.2 on 2022-05-25 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='订单生成时间'),
        ),
    ]
