# Generated by Django 2.2.2 on 2022-06-01 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='发布人')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('be_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='公告发布时间')),
                ('content', models.CharField(max_length=168, verbose_name='公告内容')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('fail_reason', models.CharField(max_length=168, null=True, verbose_name='未通过原因')),
            ],
            options={
                'db_table': 'announcement_announcement',
            },
        ),
    ]
