# Generated by Django 2.2.2 on 2022-05-25 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=30, verbose_name='车牌号')),
                ('in_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='进来的时间')),
                ('out_time', models.DateTimeField(blank=True, null=True, verbose_name='离开的时间')),
                ('money', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='价格')),
            ],
            options={
                'db_table': 'owner_record',
            },
        ),
        migrations.CreateModel(
            name='TypeMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=1, verbose_name='1包月 2业主 3非业主')),
                ('money', models.DecimalField(decimal_places=2, max_digits=5, max_length=10, verbose_name='每小时单价')),
            ],
            options={
                'db_table': 'owner_type_money',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='车主名称')),
                ('car_number', models.CharField(max_length=30, unique=True, verbose_name='车牌号')),
                ('type', models.IntegerField(default=2, verbose_name='1包月 2非包月')),
            ],
            options={
                'db_table': 'owner_user',
            },
        ),
    ]
