# Generated by Django 2.2.2 on 2022-06-01 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True, verbose_name='区域名称')),
                ('money', models.DecimalField(decimal_places=2, max_digits=5, max_length=10, verbose_name='每平方/钱')),
            ],
            options={
                'db_table': 'proprietor_area',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(verbose_name='楼层号')),
                ('unit', models.IntegerField(verbose_name='单元号')),
                ('house', models.IntegerField(verbose_name='房屋号')),
                ('square', models.DecimalField(decimal_places=2, max_digits=5, max_length=10, verbose_name='平方米')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='业主id')),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprietor.Area', verbose_name='区域id')),
            ],
            options={
                'db_table': 'proprietor_house',
            },
        ),
        migrations.CreateModel(
            name='RepairInto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=168, verbose_name='故障原因')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='唯一标识')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='报修人的手机号')),
                ('img', models.CharField(max_length=268, verbose_name='故障图片url')),
                ('be_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='报修时间')),
                ('account_repair_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='维修人员id')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprietor.House', verbose_name='房屋id')),
            ],
            options={
                'db_table': 'proprietor_repairinto',
            },
        ),
    ]
