# Generated by Django 2.2.2 on 2022-06-01 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proprietor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(default='', max_length=15, verbose_name='区域名称'),
        ),
        migrations.AlterField(
            model_name='repairinto',
            name='account_repair_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='维修人员id'),
        ),
    ]
